services:
  postgres:
    image: postgres:17.0
    container_name: estabelecimento
    environment:
      POSTGRES_DB: estabelecimentodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always